export const Lang: Record<string, Record<string, string>> = {
    cates: {
        audio: '音频',
        blocks: '方块',
        combat: '战斗',
        "core-shaders": '核心着色器',
        cursed: '诅咒',
        decoration: '装饰',
        entities: '实体',
        environment: '环境',
        equipment: '装备',
        fonts: '字体',
        gui: '界面',
        items: '物品',
        locale: '本地化',
        modded: '模改',
        realistic: '写实',
        simplistic: '极简',
        themed: '主题',
        utility: '实用',
        "vanilla-like": '类原版',
        adventure: '冒险',
        economy: '经济',
        food: '食物',
        "game-mechanics": '游戏机制',
        library: '支持库',
        magic: '魔法',
        management: '管理',
        minigame: '小游戏',
        mobs: '生物',
        optimization: '优化',
        social: '社交',
        storage: '存储',
        technology: '科技',
        transportation: '运输',
        worldgen: '世界生成',
        atmosphere: '氛围',
        bloom: '泛光',
        cartoon: '卡通',
        "colored-lighting": '彩色光照',
        fantasy: '奇幻',
        foliage: '植被',
        high: '高',
        low: '低',
        medium: '中',
        "path-tracing": '路径追踪',
        pbr: '物理渲染',
        potato: '低配',
        reflections: '反射',
        screenshot: '截图',
        "simi-realistic": '半写实',
        shadows: '阴影',
        challenging: '挑战性',
        "kitchen-sink": '大杂烩',
        lightweight: '轻量',
        multiplayer: '多人游戏',
        quests: '任务',
        "vanilla+": "超越原版",
        skyblock: '空岛',
        "map based": '基于地图',
        exploration: '探索',
        'sci-fi': '科幻',
        'small / light': '小而轻',
        'combat / pvp': '对战竞技',
        'tech': '科技',
        'adventure and rpg': '冒险与RPG',
        'ftb official pack': 'ftb官方包',
        hardcore: '硬核',
        'mini game': '小游戏',
        'extra large': '超大型',
        horror: '恐怖',
        "miscellaneous": "杂项",
        "cosmetic": "美化",
        "education": "教育",
        "map and information": "地图和信息",
        "addons": "插件",
        "armor, tools, and weapons": "盔甲,工具,和武器",
        "redstone": "红石",
        "performance": "性能优化",
        "bug fixes": "错误修复",
        "modjam 2025": "*",
        "creativemode": "创造模式",
        "mod support": "前置模组",
        "models": "模型",
        "tweaks": "微调",
        "steampunk": "蒸汽朋克",
        "traditional": "原版改良",
        "medieval": "中世纪的",
        "animated": "动画",
        "modern": "现代",
        "data packs": "数据包",
        "font packs": "字体包",
        "semi-realistic": "半写实"
    }
}